依然是很菜很菜。开始的时候有些迷惑，后来想了想原来就是给你 ~N~ 个整数取 6 个有多
少种组合。然后在做一定的输出处理的题目。想到的有递归和初步的 DFS，可是都不太会写。
就写了一个很土的程序。土的掉渣。输入输出还是不熟练，提交了三次才 AC。没脸见人了。
加油加油！

#+BEGIN_SRC cpp
#include <iostream>
using namespace std;

int main()
{
  const int max_number = 15;
  int numbers;

  int set[max_number];
  int cases = 0;

  while (1) {
    cin >> numbers;

    if (numbers == 0) {
      break;
    }

    cases++;

    if (cases >= 2) {
      cout << endl;
    }

    for (int i = 0; i < numbers; i++)
      cin >> set[i];

    int i0, i1, i2, i3, i4, i5;

    for (i0 = 0; i0 <= numbers - 6; i0++)
      for (i1 = i0 + 1; i1 <= numbers - 5; i1++)
        for (i2 = i1 + 1; i2 <= numbers - 4; i2++)
          for (i3 = i2 + 1; i3 <= numbers - 3; i3++)
            for (i4 = i3 + 1; i4 <= numbers - 2; i4++)
              for (i5 = i4 + 1; i5 <= numbers - 1; i5++)
                cout << set[i0] << " " << set[i1] << " "
                     << set[i2] << " " << set[i3] << " "
                     << set[i4] << " " << set[i5] << endl;
  }

  return 0;
}
#+END_SRC

顺便，昨天搞了个行者无疆单车知识入门讲座，比较轰动，草坪上搭起了大大的本营帐篷，
七八辆车，二十多个人，我使出浑身解数，定车、俯卧撑、拆车修车、旅行经历等等。整个
讲座还算比较精彩，从 7 点一直唠叨到 10 点 20 左右。已经有些冷了。于是借了辆车回
到 YQ。拉力听讲座的有大二的，也有博二的。讲完了一个小 dd 跑过来跟我说“谢谢你，学
长”，好可爱；有个博二的说我“非常成熟”，有几个 mm 被我讲的羞答答的，大概是受不了
行者的 ws 之风了；还有几个 wsn，中途跑到校友林里面小便，我甚至都能听到嘘嘘声音，
何况 mm 会羞了。后来我也去尿了一泡……

实验室又来了项目。所以今天告别了亲爱的 Gentoo 先生，回到了 VS 2008 的怀抱。大体
来说是做一个嵌入式平台上模仿 iPhone 界面的东西。引擎什么的基于已有的几万行代码。
其实去年已经初步接触这个项目，只是课程太忙，时间上安排不过来。这次老师也实在是缺
人了，把我这么菜的也拉了过来。一个毕业的研究僧学长领头，还有两个研究僧是主力。两
个刚考完研的大四同学每天从下沙赶来，怪辛苦的，不过他们水平实在太菜，连 C++ 都不
会，还得我教……看来我菜，有人比我还菜……

主要战略就是在实验室泡二十天，争取能搞出点成果来。将来简历上也好有点东西。否则一
片花拳绣腿，怕是饭都吃不饱了。

不过头疼的还是课程。算了，赶时间补吧。还有 289 道 ZOJ 题目。还有 LPI。顺便有空再
去刷一次我那可怜的六级成绩。

over。再来一道 ZOJ。
