[[/user_files/cnlox/Image/life/Image(108).jpg]]

这是 3 月25日晚上的照片。

首先是解决了 Emacs 和ibus输入法冲突的问题，总结起来，大概原因有三：

一是系统环境变量  LC\_CTYPE 设置错误，应该设置城 zh\_CN.UTF-8，下面是我的  locale:

#+BEGIN_SRC sh
    LANG=en_US.UTF-8
    LC_CTYPE=zh_CN.UTF-8
    LC_NUMERIC=en_US.UTF-8
    LC_TIME=en_US.UTF-8
    LC_COLLATE=en_US.UTF-8
    LC_MONETARY=en_US.UTF-8
    LC_MESSAGES=en_US.UTF-8
    LC_PAPER=en_US.UTF-8
    LC_NAME=en_US.UTF-8
    LC_ADDRESS=en_US.UTF-8
    LC_TELEPHONE=en_US.UTF-8
    LC_MEASUREMENT=en_US.UTF-8
    LC_IDENTIFICATION=en_US.UTF-8
    LC_ALL=
#+END_SRC

 二是没有设定好正确的 IBus 启动环境，应该在系统启动文件（如  ~/.xprofile,
~/.xinitrc 等，看系统版本而定）中加入如下语句：

#+BEGIN_SRC sh
    export XMODIFIERS="@im=ibus"
    export GTK_IM_MODULE="ibus"
    export QT_IM_MODULE="ibus"
    ibus-daemon -x -d -r
#+END_SRC

三是字体问题。昨天出于系统洁癖原因，卸载了 Xorg-11，装上了  xorg-server 更精简的包，这么一卸一装少了几十款恐怕一辈子都用不到的字体。可是 Emacs 却无法使用 IBus 输入法了。无奈，重新装上 Xorg-x11，重启后问题得到解决。

有的论坛说修改一下 Emacs 中ctrl+space快捷键的设置。其实不对的。默认情况下 xim 快捷键的优先级应该比 Emacs 的快捷键高，ctrl+space默认应该被 x 系统截取，调出 IBus 输入法的。

解决完了 IBus 的问题，晚上去 zjg 做实验，还是 Verilog，只是这次换了两台电脑，依然没有找到“成品”。无奈只得自己动手丰衣足食。好在照着前人的一份实验报告，折腾了良久，竟然成功了。三个仿真一个板载，运行成功。天，有史以来第一次靠着自己的力量搞懂了 Verilog 代码完成了实验。不过 xilinx 还是比较恶心。bug不断，所谓下载到板子上究竟是怎么回事，鬼才知道。学生也就就着糊涂装糊涂，copy来 copy 去，索然无味。不过好好学还是有收获的，逻辑，组成加体系结构，三门理论碰上三门实验，抵得上国外大学体系结构的真家伙了。

无奈做完实验已经没有公交了，等校车又得等半个小时，给某人打电话，心境不佳，索性走回 yq。十三公里左右，从 9 点半走到 11 点半。

路上碰见一家超市，遂进去拿了凭雪花，勇闯天涯，心情舒畅，大快。边走边饮，边饮边唱，边唱边笑，放浪形骸。爽也。路上短信和 wj 大谈 Linux 发展之路，指点江山，激昂文字，好不快活。

晚上回寝，随便逛了逛论坛，倒头便睡。至日照三杆，吃过午饭，步行至图书馆。一个下午，看了两章《Linux
Administration
Handbook》，搞定了 zhq 社团的文案，还写了一篇煽情的文字给两位同志，ms很有效果。

9点回寝，执笔给高中老师写了一封信，兑现自己之前的一个承诺，总结了下自己的过去，展望下未来。mm说，“是否工作疲惫，生活劳累，这时候停下脚步，回头看看自己走过的路，又会充满前行的动力”。也对的。明天早起写完两天报告，补补课。后天去 zjg 做一个单车入门讲座。实验室学长给我短信，说有个项目，需要连续奋斗二十天，问我是否有意。我还在犹豫，恐怕不得安排。要看的 lpi，要补的课，要刷的 ZOJ 题目，反正，总算进入学期正轨了。

加油吧。奋斗的日子。再这样下去，每天日照三杆，恐怕不行。以后恐怕要以实验室和图书馆为家了。Knuth说，程序就像蓝色的诗歌，本人东施效颦，以代码格式贴上这首歌：

#+BEGIN_SRC sh
    《我们都站在雨中》---- 《连城诀》主题曲 

     把双眼紧闭  , 剑要往哪里刺去 
     谁说秋风最能懂落叶思绪 
     致命的一击  , 真的对手是自己 
     只剩下了无声的叹息 

     酒逢知己  , 千杯也难尽兴 
     英雄醉了也一样会慢慢倒下去 
     望星辰转移  , 江湖又下起暴雨 
     我们都站在雨里 
     穿过刀光剑影之后  , 我还是那个我 
     只是把受伤的心独自对着明月说 
     天涯的尽头有没有一处安静的角落 
     让浪迹的人在走累的时候躲一躲  
#+END_SRC

 安。
