去年换 x201i 的时候，曾经折腾出一篇《[[http://xiaohanyu.me/posts/2011-01-30-x86-64-arch-linux-on-thinkpad-x201i/][x86-64 Arch Linux on ThinkPad x201i]]》，后来
x201i 陪我度过了毕业半年最为艰难的岁月，表现可圈可点，配合我自己调制的 Arch
Linux，系统非常高效，让我在 4 个月的时间内搞定了 8 门课程、毕业设计，还看了不下
二十部电影和纪录片。

说起操作系统重装，我也算究竟沙场了。基本上每半年会重装一次操作系统，从 XP，Vista，
RedHat 9.0，Fedora，到 Ubuntu 8.x，转向 Arch Linux、Gentoo，甚至在华数淘宝实习的
时候还装了 4 台 PC 和 2 台 Dell 的 PC Server。最长的一次要属第一次接触 Gentoo 的
那次，装操作系统装了有 2 个星期，折腾了两个月，终于发现这个东西不符合低碳节能的
基本要求，再一次不小心的 fsck 误操作中彻底结束了 Gentoo 之旅，回到了 Ubuntu 和
Arch的怀抱。

来到百度第一天领到的新笔记本，x220i，好家伙，上网一搜，居然是今年最新款的 X 系列
ThinkPad。CPU 是新一代的 SNB 架构。默认系统的十年前的 XP。本来我想另辟空间再装个
Linux 来个双系统，后来 XP 实在用着不爽，遂全盘格式化，全部分给 Arch Linux。

我一直有一个疑问：为什么 Windows 的命令行，无论是 CMD 还是 PowerShell，不能实现
最简单的窗口最大化功能？

OS 版本用的是 [[http://linuxtoy.org/archives/arch-linux-2010-05.html][Arch Linux 2010.05]]，在 [[http://mirrors.sohu.com/][mirrors.sohu.com]] 上下载 [[http://mirrors.sohu.com/archlinux/iso/2010.05/archlinux-2010.05-core-dual.iso][支持 32 位及 64 位
架构的 Dual映像]]，用 UltraISO 刻录硬盘镜像到 U 盘上。本以为 Arch Linux 的安装会像
以前一样轻车熟路，不曾想这次却遇到了以前从来没有遇到的一个大麻烦：网卡无法识
别！！！

不能上网就意味着不能装 X，不能装 X 就意味着没有 Firefox，没有 Firefox 就意味我不
能上网来写这篇博客。无奈之下，去同事的机器上下载了最新的 [[http://blog.linuxmint.com/?p=1760][Linux Mint 11]]，痛快装好，
网卡这次能用了。

Google 搜索，发现 Arch Linux 2010.05 是 2.6.32 的内核，而 Linux Mint 11 是
2.6.38 的内核，因此我怀疑是不是 Arch Linux 内核比较老而 X220i 架构比较新的原因。
搜索的过程中发现了一个叫做 [[http://wiki.archlinux.org/index.php/Archboot][ArchBoot]] 的项目，说白了就是半官方的 Arch Linux 滚动更
新 ISO。热切的下载了最新的 ArchBoot 刻录安装，但是不幸的是这个 ArchBoot 在我的笔
记本上根本无法启动。

怎么办？要不重新叫 IT 部门的人重装下 XP？还是先用一段时间的 Mint，等下一个
Arch Linux 的官方安装版？

但我终究是忍不住的。电脑之于黑客，相当于宝剑之于剑客。没有顺手的系统，自然没有高
效的工作和良好的心情。

于是不得不换一种思路：尝试手动去下载 Intel 网卡的驱动，然后编译安装，搞定网卡驱
动后再联网升级到新的内核。事实证明这个策略是奏效的，所需要的网卡驱动程序可以在
Intel 的网站上[[http://downloadcenter.intel.com/Detail_Desc.aspx?DwnldID=9180][下载]]。安装过程不再赘述，按照安装包里的说明即可。装好驱动后升级内核，
装 X，装 KDE，简单配置下字体，一切顺理成章，不亦乐乎。

最后的两个问题依然是驱动相关。一个是显卡的问题，这个可以通过更新内核来搞定。一个
是 ThinkPad 风扇的问题，x201i 上的方案迁移到 X220i 上并不奏效，tpfand 基本不可用。
好在有 thinkfan，通过 yaourt 安装下。设置主要参考[[http://apps.hi.baidu.com/share/detail/39726097][这里]]，但是原文中所设置的：

#+BEGIN_SRC sh
sensor /proc/acpi/ibm/thermal (0, 3, 3, 2, 10, 0, 10, 0, 2, 2)
#+END_SRC

并不存在。在 X220i 上的 =/etc/thinkfan.conf= 设置为：

#+BEGIN_EXAMPLE
# I use this on my T61p:
#sensor /proc/acpi/ibm/thermal (0, 10, 15, 2, 10, 5, 0, 3, 0, 3)

# (0,   0,   55)
# (1,   48,     60)
# (2,   50,     61)
# (3,   52,     63)
# (4,   56,     65)
# (5,   59,     66)
# (7,   63,     32767)

sensor /sys/class/hwmon/hwmon0/temp1_input (0, 3, 3, 2, 10, 0, 10, 0, 2, 2)
(0, 0, 45)
(1, 45, 48)
(2, 48, 55)
(3, 55, 58)
(4, 58, 60)
(5, 60, 63)
(6, 63, 65)
(7, 65, 32767)
#+END_EXAMPLE

经过此番修整，x220i 终于被我调教的舒舒服服，服服贴贴。至于旧爱 x201i，简单修整了
一下给妞用了。

最后许个愿望吧：希望在未来可见的三年内不要再折腾操作系统了。同时遥祝远在
Singapore 的阿黎早日搞定 MacBook 上的 Ubuntu，整好 MitSIM，顺利毕业。嘿。
