还有两个小时就要踏上去往哈尔滨的旅程。回首 2011，颇多感慨。这一年我 23 周岁，从 16 岁离家求学至今，这是第七个年头。这一年的标志性事件就是我开始正式从学校走向社会，实现经济独立。其余的一切，基本上都是围绕着这条主线在转。

<<table-of-contents>>
** Table of Contents
<<text-table-of-contents>>

- [[sec-1][1 学业  ]]
- [[sec-2][2  工作  ]]
- [[sec-3][3  经济  ]]
- [[sec-4][4  专业  ]]
- [[sec-5][5  阅读  ]]
- [[sec-6][6  观影  ]]
- [[sec-7][7  旅行  ]]
- [[sec-8][8  社交  ]]
- [[sec-9][9  展望  ]]

#+BEGIN_HTML
  <div id="outline-container-1" class="outline-2">
#+END_HTML

** 1  学业  
#+BEGIN_HTML
  <div id="text-1" class="outline-text-2">
#+END_HTML

2011 年上半年的主题就是学业了。具体说来，就是我为了所谓一个学位的虚名，
每天殚精竭虑，为了最后的几门考试和毕业设计奔命不息。3月 1 日回校，7月 5 日拿到毕业证，6日离杭。这期间混过 10+ 门课，外加一门毕业设计。至此对中国的学术体系彻底失望，再也不想回头。

临毕业之际，许多人邀我参加各种活动，除了少数不得不去的几个，诸如旅行者毕业散伙饭，其余则一律回绝。*有些人散去之后，终究不会再见，索性随缘，何必再添一场饭局、游戏，徒增无趣？*

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  <div id="outline-container-2" class="outline-2">
#+END_HTML

** 2 工作  
#+BEGIN_HTML
  <div id="text-2" class="outline-text-2">
#+END_HTML

2011 年下半年的主题是工作。我所在的小组负责百度 Hadoop 集群的运维工作。面对着 15000+ 的机器资源，如何更合理的利用、管理这庞大的资源，对于我们是一个巨大的挑战。

其实纵观业界，开源的 Hadoop 生态圈已成，各种周边工具诸如 chukwa、ganglia、
nagios等已经比较成熟，但是如运维这些成套的系统，每个公司却有每个公司 
 的不同做法了，这也是一个 IT 公司安身立命、独立于世的重要资本。

开始的时候，由于新人入职，学习培训，加上组内的照顾，自觉工作十分有趣。
到 10 月份，在真正接手集群的时候，事情陡然增多，各种会议沟通、预算报表让 
 我十分疲惫，加上部门人员变动，新来的老大和我脾气并不对味，因此让我萌生了要走的念头。

Anyway，在百度，我见识到了巨型公司运营的基本流程，接触到了浩瀚如海的机器资源以及相伴而来的各种故障，并有幸和牛人们一起并肩战斗（虽然我是为他们提供底层服务的 ......），这一切的一切，让我受益匪浅。

两年内，从我正式开始认真学习计算机开始，我从一个小破烂的实验室，到淘宝的实习，再到百度的分布式运维小组，平台越来越大。只不过，随着平台的扩大，
其所带来的沟通成本也会倍增。在百度，我平均每天发十五封邮件，每天花  3-5 个小时在聊天工具上，每周至少开 3 个会，每周至少写两份文档（包括周报），
这一切的一切大大得压缩了我学习底层技术、编写代码的时间。所以我决定离开，嗯，在年后。

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  <div id="outline-container-3" class="outline-2">
#+END_HTML

** 3 经济  
#+BEGIN_HTML
  <div id="text-3" class="outline-text-2">
#+END_HTML

2011 年的一个重要人生里程碑是我第一次实现了经济独立，并且在年底 12 月份初的时候成了一个所谓的“万元户”。如果说，学生时代，是有钱没时间，那么，
工作时代，就是有时间没钱。我希望，在下一个七年，等到我三十岁的时候，能够实现一种高层次的财务自由。

说到底，我依旧是个俗人，逃脱不了俗世的纷纷扰扰。所谓自由，有的时候，不是自己想干什么就可以干什么，而是自己不想干什么的时候，就可以不干什么。

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  <div id="outline-container-4" class="outline-2">
#+END_HTML

** 4 专业  
#+BEGIN_HTML
  <div id="text-4" class="outline-text-2">
#+END_HTML

2011 年，我在专业技能的提升方面并没有达到我的预期，但是已经做到尽心尽力。

2011年下半年的专业关键词是 Lisp。在  8-12 月4个多月的时间里，除了工作上的需要，偶尔分神去学习下 Java 和Hadoop的相关知识，剩余的大部分精力都放在了 Lisp 的学习上。

学习 Lisp 让我发现了编程语言的另一个世界，正如学习 Linux 让我发现了操作系统的另一个世界。我在 Lisp 身上找到了很多以前我学习的编程语言不曾体会到的东西，诸如交互式的编程环境、简单和谐的 S-expression、强大的 macro，等等等等。我觉得，通过 Lisp 的学习，我开始逐渐登堂入室，窥得计算机科学的本质。
我开始理解了很多以前不曾理解、似是而非的概念，诸如 code is data、序列化、
xml与 Ant，我现在能以 Lisp 的观点重新审视 MapReduce 编程模型，而 SICP 的前两 
 章内容，更让我领略到了 combination 和abstraction的绝妙组合。

2012，我希望我在 Lisp 学习上的道路上更进一步，完成所有 SICP 的习题，完成 
《On
Lisp》的阅读和《PAIP》，并且深入学习计算机领域的另外一本经典书籍 ------《深入理解计算机系统》。我觉的 SICP 和CSAPP代表了计算机科学的两个方向，前者讲的是计算的本质，也就是编程语言和数学，后者讲的是计算机，也就是编程语言的底层支撑。

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  <div id="outline-container-5" class="outline-2">
#+END_HTML

** 5 阅读  
#+BEGIN_HTML
  <div id="text-5" class="outline-text-2">
#+END_HTML

2011 年我依旧保持着优秀的阅读习惯和进度，即便是在百度繁忙的工作之余，我 
 也会保持每周  20-30 个小时的独自阅读时间，我以此为荣，并以此作为我以后安身立命、闯荡江湖的资本。我非常享受这闲暇的时光，再也不用为了考试、分数去阅读，我可以递归的去阅读自己感兴趣的任何资料，从 Scheme，到 Lisp，到 
emacs，到 ai，所读无穷、所识无尽，所乐无限。

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  <div id="outline-container-6" class="outline-2">
#+END_HTML

** 6 观影  
#+BEGIN_HTML
  <div id="text-6" class="outline-text-2">
#+END_HTML

2011 年我的观影活动极其频繁，整整一年，我大概看了不下 170 部电影和电视剧，
还不包括重温以前的一些经典片诸如《暗算》、《亮剑》等等。

重点推荐：

- 吴晓波《激荡三十年》
- 俞敏洪《创业传记》
- 《迁徙的鸟》
- 《猫咪物语》
- 《谍影重重》

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  <div id="outline-container-7" class="outline-2">
#+END_HTML

** 7 旅行  
#+BEGIN_HTML
  <div id="text-7" class="outline-text-2">
#+END_HTML

2011 年我并没有大的旅行动作和计划。而事实上，除了 08 年那次杭州到拉萨 45 天疯狂的旅程，旅行之于我，随着年月的逝去，从一个压抑很久的梦想，逐渐的演变成一种北大教室内静静读书的安详。

我不希望做一个旅游暴发户。所以对于《背包十年》，一笑而过。我觉得，*旅行者没有必要把旅行说的那么高尚，这个世界需要一往无前的行者，也需要在各个岗位上日复一日的工人 *。《背包十年》的作者说白领的工作是“每分每秒都很精 
 致，但每分每秒都是无聊”，未免太过偏激，对自己的生活太过傲娇，我想，他这辈子大概也不会体会到数学和计算理论的和谐之美了。

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  <div id="outline-container-8" class="outline-2">
#+END_HTML

** 8 社交  
#+BEGIN_HTML
  <div id="text-8" class="outline-text-2">
#+END_HTML

2011 年并没有重量级的良师益友在我的生命中留下印记。一方面是由于我个人逐渐收敛自己的社交圈，将自己有限的时间精力放在一些更值得我去思考、去做的事情上，另一方面也许是年岁增长，并步入职场的缘故。

人生苦短，诱惑太多。我们生命中  90% 的人，到头来大家不过是一场过客。*随遇而安，随缘而乐 *。*对于人际关系，该说不的饭局就说不，省下的宝贵时间，留给自己，即便是空虚寂寞，也会让自己更加明了自己不喜欢什么，这就有希望能够找到自己更喜欢的东西。*

找到自己喜欢的东西，人生的一切快乐皆来源于此。

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  <div id="outline-container-9" class="outline-2">
#+END_HTML

** 9 展望  
#+BEGIN_HTML
  <div id="text-9" class="outline-text-2">
#+END_HTML

 总的来说，2011年至于我，说不上丰富，却多了一份安定与安详。我想明白了很多道理，也开始明白，生活不仅仅是要做加法，必要的时候，也要做一些减法。
在人生 60 多年的旅程中，背负太多的东西，只会让你走的更慢。

想下海游泳，就要脱掉身上的衣服；想登高而呼，就要卸下身上的重担。2012，
我来了。

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  </div>
#+END_HTML

 
