世间唯有两样东西能够深深地震撼人们的心灵，一是我们心中崇高的道德准则，二是我们头顶上灿烂的星空。
------康德 

 两年前我大三，刚刚过了几门纠结的考试，找到华数淘宝的实习，正式开始了自己的职业生涯。在华数淘宝，我第一次做出了点影响世界的产品  ------ 我写了一套视频转码上线系统，经这套系统转换格式入库后的视频至今还在  [[http://www.taohua.com][ 淘花网  ]] 上播放着。

四年前我大一，也是刚刚考完十几门不痛不痒的考试，我一边告诉母亲自己会在一周后回家，一边又在宿舍里面擦拭着自己的爱车，想着路上该怎样向母亲赔罪。那个暑假我一个人，一辆单车，一路风雨，无阻无悔，孤旅天涯：

“十元钱的小镇旅馆，半夜竟然被雷震醒，不足半平方米的窗子，依然挡不住闪电，那耀眼的光芒，直插我狂野的心。无比的想念某人，我知道，家乡的老妈妈也无比的想念我。窗外的雨，是妈妈您思念晗宇的泪吗？知道你已经收拾好了一切，就等晗宇回去，给我做好吃的，却收到我的短信。我知道这很残忍，发那条短信的时候，我的心和手一样的发斗。对不起了，妈妈，又让您操心了。二十岁了，二十岁是人生最灿烂的年岁，我要去追寻我的梦了。我不想呆在家里浪费自己的青春。很多时候事情是不能拖的。对不起了，妈妈。我想，当我老了的时候，回忆起这段岁月，我会笑的。”

45天，2500公里的骑行，500公里的水运，1500公里的汽车旅行，4000元的开销，明月夜那个朦胧的终点。可我在拉萨只待了 12 个小时，其中还包括青旅里 8 个小时的酣睡。回到拉萨，回到布达拉，郑钧先生在创作这首歌的时候，可有想过，他的听众也许并不知道他没有去过拉萨？

六年前我高二，那一年我决定放弃数学竞赛转攻化学，并且第一次来到北京，单日往返，不吃不喝，在西单王府井买了 400 块钱的书籍。那年三月我和 WP 以搞竞赛为名、逃避月考为实来到北大，买了几本北大的化学书，还听了一节《[[http://book.douban.com/subject/1672586/%20][基础有机化学 ]]》作者裴伟伟教授的基础有机化学课程，课后 WP 去找裴伟伟索要签名，教授问，你是哪个学校的，WP答道，我是唐山一中的！
那个时候听课的态度真是认真到了极点，我们在教室里自己摸索奉为圭臬的教材，如今见到作者本人了，还是个活的，怎能不激动呢？咦，怎么还有学生迟到，在教室里偷偷吃早餐？

那年的暑假我第一次走出河北省，坐上火车来到了美丽的西子湖畔，参加一个奥数培训，培训费用 400，车票也要 400。我有幸见到了几何大王叶中豪先生，他出神入化的几何画板演示着实令我颇为震撼。那个夏天我第一深切地感受到了南方火炉城市的火热。尤记得天热，一行人等想去网吧打魔兽，但是又有些犹豫不决，于是就有人提议说掷硬币吧  ------ 正面，去魔兽；反面，去魔兽；硬币立起来的话，去培训学习  ...... 结果可想而知。除了西湖，我还去逛了逛浙大的西溪和湖滨校区，感觉毫无特色，都特别破，还下定决心，如果将来能保送了尽量不来浙大。其实浙大校区的精华在玉泉、之江、华家池和紫金港校区，而那个时候的我连上网都不会，就更不必说自己游玩了。

八年前我初四，刚刚中考完。校长告诉我们说唐山一中是东北三省华北五省最好的中学，于是乎，在校长和父母的殷切期待中，我第一次走出承德市的地界，去参加唐山一中理科实验班的入学考试。由于我和父亲都不太懂城市的公交车系统  ------ 我一直以为城市里的公交车和家乡的“招手停”是一样的，第一次上公交车的时候还被门给夹住了  ...... 我和父亲决定走路去火车站找相对便宜的旅馆  ------ 学校附近的旅馆要 30 块钱一个床位，而我们在火车站找到的旅馆只要 10 块钱一个床位。考完后感觉很糟，去看成绩，和自己估计的也差不多，236，彻底没有希望了；后来同去的人说我考了 260，我不信，又去看了下，果然是 260，不过兴奋过后就是失落，因为分数终究不够正取线，还差十几分，只能收拾行李回家了。走之前又去书店买了几十块钱的书，被父亲唠叨了，说身上钱有些不够了，别买书了。回家后被告知说可以去唐山一中，但要交 20000 的择校费，我自然是眼巴巴地想去，可怜我父母，刚刚还了别人 20000 大洋，又得去借回来供我上学。就这样，我稀里糊涂的进了唐山一中，进了河北省最好的省理科实验班，虽然考过班级倒数第二但依然顺利的实现了自己的保送理想，提前进入浙大，并幸运的接触到了旅行者，又幸运地体验到了批量挂科的感觉  ......

 半年前我去了趟长白山，寒冬的天池，白茫茫一片，仿佛到了世界的尽头，我隐约感觉到我的生活似乎要发生什么变动  ------ 果不其然，回来后我就从百度离职了，尽管我来到北京的时候是打算干三年的。铁打的团队，流水的兵，有的时候，老大需要的是执行命令的兵，而不是有想法的人。不过我依然感激百度教给我的一切，加起来 9 个月的实习和正式工作，不长也不短，技术上长进有限，但是我却看到了，一个如此规模的公司，其内部的组织机构和运转机制，而这些在书本上学校里是学不到的。

我并没有急着去找新工作，而是计算了下手中的钱，做出了一个“偷得浮生半年闲”的决定  ------ 我决定借着近水楼台先得月的优势，去北大待上三个月，重点任务是泡图书馆，写写代码，顺带看几场电影，游几次泳。

春节我在家待了三周，待过了元宵，离家数年第一次在家过个元宵节，圆了母亲的一个愿；我看完了 SICP 前两章，完成了 100 道题目，对编程语言有了进一步的认识。

三月我再次回到家中，这次是为了弟弟中考的事情，我替他跟老师请了假，晚上在家单独辅导他，我并没有填鸭式的讲解，相反，我会给他看优酷上化学实验的视频，我会亲自给他做一个针孔照相机来给他讲解光学，我会给他讲解基础的英语音标和语音，让他通过发音来读记单词，我给他买了张道真的语法书让他自己查询解决问题，我会给他讲解整个数系发展的故事让他去理解实数，我会给他讲解大学的故事，让他对未来有美好的憧憬，还会给他放一些电影如《迁徙的鸟》，让他去触碰下心灵中柔软的地方。这几日他中考完来到北京，我训练它骑车旅行，我给他讲解基础骑行知识，让他自己通过网络查询确定骑行路线，制定训练计划。昨日，他一个人骑车从北京到天津，150公里，一日完成，我甚感欣慰。

四月回到北大，妞找到了实习，我则专心致志的“替”妞泡图书馆，再也不用担心有人过来跟我抢电脑。就这样赋闲下来，就这样奢侈地享受了一个又一个美好的午后，就这样奢侈地徘徊在北大图书馆排排书架里，随便抽一本书，即使不读全书，读读序言目录看看作者那么牛崇拜一下的感觉也是很不错的。本科的时候我一直想找块时间，好好泡一下图书馆，奈何前两年醉心户外和社团，后两年又疲于奔命与毕业，这个愿望一直没有实现，成了我大学生涯一个莫大的遗憾。今天我终于得偿所愿，我用自己攒的钱，给自己放了 6 个月的假，这六个月里我看了三四十本书，写了三四万行的代码，我不为老板打工，不为考试成绩，更不为发表 Paper，我学习看书泡图书馆，乃是境由心生，学从乐起。

但是生活还要继续 ^{[[fn.1][1]]}，在经历了豆瓣  / 人人  / 雅虎北京  /iHandySoft/ 易云捷讯持续两周高强度的面试后，我最终从了易云捷讯，一家才成立一年的创业公司。创业公司总是风险与机会并存，而创始人的诚意确实打动了我，让我非常感动。我一直自傲的认为自己的身上具有创业者的气质，我也坚信自己在经过一定的积累后，一定会做出一些改变世界的东西。学者、行者和企业家，这是我目前给自己定的几个可选的人生方向，现在来看，技术起步的企业家也许是我更可能走的路。
*我一直认为行者气质和企业家气质有很多相通之处，不安分，爱折腾，独立自主的想法和判断能力，加上虽千万人吾往矣的勇气。我一直想创业，只是没想到这么快而已。*

“从六楼俯视校园，各种树木摇曳着缤纷的绿，映着高楼和远山。而在寒冷的冬天里，缤纷落尽，繁华消亡，只留下黑色或褐色的枝干，如一支支手伸向清白的天空。可是这些光秃秃的枝干就是树的本来面目吗？冬日看去，便觉万物终归于寂，可是后面还有个春天，有那黝黑的枝干上刹时间涌出绿芽的生机。我总觉得在这些苦难的背后，有什么力量正在生长 ^{[[fn.2][2]]}。”

半年前我来到北大的时候，北大尚未开学，教室和图书馆都关着门；半年后我要开始工作离开北大的时候，暑假已经开始，教室和图书馆又都关了门。我看着这苦难背后的力量从无到有，从萧瑟到繁华，心中不断地提醒着自己，即使“缤纷落尽、繁华消亡”，青春绝版，也  * 不要被生活磨平了棱角 *
。

仅以此文，纪念那一个个美好的未名湖畔图书馆中阳光四溢的午后。

<<footnotes>>
** Footnotes:
   :PROPERTIES:
   :CUSTOM_ID: footnotes
   :CLASS: footnotes
   :END:

<<text-footnotes>>
^{[[fnr.1][1]]}
我去面试豆瓣的时候，豆瓣网的耿新跃老师问我为何离职为何现在又找工作，我就大概解释了一番，于是就有了这句话，至于内涵嘛，你懂的。

^{[[fnr.2][2]]} 这段话是一个 IMO 满分金牌得主的文字，
[[http://blog.sina.com.cn/s/blog_62178a2b0100mwpb.html]]。

 
