仿佛转瞬间北京就入秋了，凉风习习，晚上睡觉要关上窗户盖厚被子了。转瞬间我在新公司工作已两月有余，工作不算繁忙，博客却荒芜至今，也是时候该写点东西除除草了。这半年来读了不算少的书，也写了一些“虎头蛇尾”的文章，文章内容从汇编、Lisp到工具配置，大体上也反映了半年来看书学习的历程。我这个人不笨，却也谈不上聪明，人长得丑，千辛万苦泡到了一个妞，捧在手心、含在嘴里，寻思着自己没钱没背景，想保住这个妞，惟一的出路似乎只有读死书死读书了。所幸的是，读了这么多年书，我对读书的兴趣正变得越来越浓，最令我感到欣慰的是，这半年来有那么几次，合上书籍闭上眼睛深吸一口气，竟颇有一点融会贯通的感觉，妙不可言。我也开始尝试，将这些转瞬即逝的”感觉“转换成文字，与大家分享，奈何功力尚浅，
*而认真的写作却有如雕刻 *
，因此前面写的几篇文章都极耗体力，让我心有余悸，不敢再轻易提笔。

工作以后，大块的无人打扰的时间会减少很多，因此在砍掉了人人、QQ之后，连手机上的新浪微博客户端也被我卸载了（我在微博上只是个看客，不时地会去搜索一些技术信息而已）。我依然保留了一些有价值的博客，并且会不定期地清理博客订阅列表。
*在碎片化的互联网海洋中，一篇好的博文如珍珠般璀璨珍贵 *
。我不喜欢加班，相反，高更青睐于高效率的工作，我会利用手头的各种工具和知识尽量用最短的时间完成更多的工作，这使得我每天在工作之余还会有至少 3 个小时的阅读时间，加上周末两天每天不少于 8 小时的阅读时间，我尽力保持每周的阅读时间和工作时间持平。恬不知耻的加一句自恋的话，咱也算是每周工作学习不少于 80 个小时的人了。

来北京以后，个人的业余生活变得越来越单调，似乎除了读书之外，就是躺在被窝里吃水果看电影了。真是难以想象，几年前自己还光着膀子天南地北地疯跑，到了北京，仿佛青蛙进了温水，一点蹦跶的力气都没了。我一直自我安慰说，廉颇未老，尚能饭也，之所以长期宅，只是因为北京众所周知的空气质量。我知道自己在自欺欺人，即便北京天空藏蓝青红，我大概也不会像以前那样骑车爬山了。归根到底，我想可能是我对浅层次的旅行失去了兴趣。”我的生活精致到每分每秒，而每分每秒都是无聊“，这是《背包十年》的作者形容对白领生活的一种评价；可是在我看来，《背包十年》充其量只是一个旅游暴发户的炫耀之作，记不得从哪里看来一句话，”
*中国的希望在于疲惫归家的工程师 * “。

我想一个人的旅行所得，终究还是要归结到这个人的思想境界上去。同样的山山水水，不同的人看来却能得出不同的山水人世的道理。我以前一直坚信，旅行能够给人生增加一个新的维度，阅读也是。现在看来，没有阅读作为支撑的旅行终究会演变成相机快门的重复性工作，日子久了，难免兴趣索然。
*旅行可以给你的生活开一扇窗，但阅读却可以给你一整片原野 *
。^{[[fn.1][1]]}

周国平说，“阅读是与历史上的伟大灵魂交谈，借此把人类创造的精神财富‘占为己有 '。写作是与自己的灵魂交谈，借此把外在的生命经历转变成内在的心灵财富。信仰是与心中的上帝交谈，借此积聚‘天上的财富 '。这是人生不可缺少的三种交谈，而这三种交谈都是在独处中进行的。”

这半年来我最大的进步就是开始逐渐懂得君子慎独的道理，我开始尝试着，在一个人心情烦躁的时候，静下来去阅读，并一丝不苟地做读书笔记。我发现，在信息爆炸的时代，用看似慢下来的原始工具爬格子，是一种绝佳的缓解压力放松身心的好方法。以前心情烦躁的时候，要么就去找几个好朋友喝酒扯淡，要么就去山水疯癫，浮生随梦的生活，毕竟只是一种逃避，每个人都要学会直面惨淡的人生，以及那茫茫宇宙中永无止境的孤单孤独。

"We are drowning in information and starving for
knowledge."^{[[fn.2][2]]}

在信息时代，我们每天似在狂欢，却不知，那只是一群人的孤单。

"我一个人吃饭   旅行   到处走走停停  ;  也一个人看书   写信   自己对话谈心  "

 学会享受孤单吧，因为  

"* 孤单   是一个人的狂欢  *"

--

<<footnotes>>
** Footnotes:
   :PROPERTIES:
   :CUSTOM_ID: footnotes
   :CLASS: footnotes
   :END:

<<text-footnotes>>
^{[[fnr.1][1]]}
[[http://www.douban.com/group/topic/22497880/][ 同学，其实你可以不用周游世界 ......]]

^{[[fnr.2][2]]} [[http://blog.pluskid.org/][Free Mind]]

 
