2012是沉淀与积累的一年。

这一年我 24 周岁，龙腾虎跃，本命之年，自离家求学已是第八个年头。这一年以一场华丽的旅行为序，以一次突如其来的辞职开场 ^{[[fn.1][1]]}，最后又以一场突如其来的家庭事故结束。这一年，宠辱不惊，去留无意，浪漫主义与现实主义并存。[[http://cnlox.is-programmer.com/posts/34489.html][北大赋闲的半年逍遥自在 ]]，工作奋斗的半年长进充实。

这一年我戒了微博，冷了 QQ，并且在有意无意地  [[http://cnlox.is-programmer.com/posts/33354.htm][ 远离各种 SNS]]。就在这一年的沉寂中，我已经和曾经天马行空般的生活渐行渐远。”要么读书，要么旅行，身体和心灵，总要有一个在路上“，这么多年以来，我一直身体力行地践行着这句话。从唐山焦躁的夏，到青海湖凛冽的风，到藏边青红的天，到西子湖畔金秋十月的桂花香，再到北京灰蒙蒙的天空，我的身体和心灵，不曾有半刻停歇。读与行就是我的 DNA 双螺旋，”行走，思考，在路上“或许会成为我一生的写照。

这一年我开始更加冷静地审视旅行，并把大部分精力投入到了阅读当中。让我忍不住欣喜的是这一年大概是我有生以来阅读状态最好的一年。读技术书籍常常能读出融会贯通的感觉，读人文书也偶尔能读得气喘吁吁，或喜或悲，甚至泪流满面。根据豆瓣上的统计，这一年我大概总共读了 60+ 的书籍，如果算上读了一半而未收尾的书籍，大概能有 70 以上了。前半年脱产的时候平均每天的阅读时间大概是 10 个小时，后半年工作后也基本能保证每天不少于 3 个小时的阅读时间。当然，作为刚刚走上社会的一枚技工，阅读上还是以专业的书籍为主。这一年我技术上的主要关注点是编程语言，我开始形成跨语言的思考能力和学习能力，在学习了基本的 Lisp 知识和函数式编程语言的基础后，我开始更加深刻的理解以前许多不曾理解的编程技术和概念。具体而言，我在 C++
98 上有了上有了很大的自信，这种自信使我在找工作时能够应付绝大多数的 C++ 面试，从 STL 到底层的一些汇编知识均有涉猎；Lisp方面我基本上学会了除了 Macro 外的 Lisp 基础知识，这点知识让我打下了跨语言思维最重要的基础；Python作为我后半年的工作语言，在 Python 标准库、TDD开发和代码技巧方面都有了长足的进步，让我的 Python 能力由脚本级进化到了工程级；我也看了三本 Ruby 的书，包括《Programming
Ruby》，《The Ruby Programming
Language》和《松本行弘的程序世界》，凭借 Lisp 和Python的基础，我在一周内就基本熟悉了 Ruby 语言的精华所在，虽然到现在还没有机会写一些实用的程序。技术之外，我也开始尝试去认真阅读一些人文书籍 ^{[[fn.2][2]]}。精彩的书籍包括但不限于林达的《近距离看美国》系列，齐邦媛的《巨流河》，柴静的《看见》，以及史铁生先生的书。夜幕窗前淡淡的灯光之下，一个人的情感随着书上的文字跳跃起伏，这种感觉很奇妙。我也开始尝试认真的写作，第一次发现，“[[http://cnlox.is-programmer.com/posts/35680.html][认真的写作有如雕刻 ]]”，因此写到后来不敢再轻易地提笔，光顾着自己阅读，孤单狂欢去了。来年，我希望自己能够在 Lisp 的路上更进一步，精通 Python，完整的掌握 JavaScript 并争取掌握一门 Web 开发框架，可能的话，再去学习一门新的编程语言。我希望能够读完史铁生全集和王小波全集。

这一年我的工作开始走向正轨。远离的大公司的扯皮和政治后，我开始真正自我主导做一些实际的事情。我熟练的掌握了 git，从而使我的工作效率进一步提升；五笔输入法的学习也初见成色，再咬牙坚持半年应该可以作为日常输入法使用；看完了 Emacs
Manual 和部分 Elisp
Manual，Emacs用起来更加得心应手。我和公司一荷兰小伙共同倡导了新的代码开发流程 (TDD+Git+Review)，或多或少地提升了工作产出和代码质量。OpenStack方面，我也开始逐渐理解其整体架构，11、12两个月写了大约 5000+ 的代码，高峰的时候 3 天左右就能完成一个实用的 feature，从前端一直写到 DB 再加上完整的单元测试，虽然由于公司限制这些代码暂时无法回馈社区 ^{[[fn.3][3]]}。我开始逐渐向一个  Full-Stack
Programmer 发展，从前端写到 DB，虽然这些代码有很多是在不了解细节的情况下照葫芦画瓢写出来的。对我而言，OpenStack是一个难得的优秀开源项目，里面有太多值得学习的东西，即便刚开始只能模仿，也受益匪浅。来年，我希望自己在网络编程和并行编程方面打好基础，在此基础上更加深刻的理解 OpenStack 核心算法和技术原理，包括但不限于 RabbitMQ，RPC，调度算法，安全等。开源方面，今年除了几个不值一提的 patch 外，几乎毫无建树，虽然自己七七八八的也写了五六万行代码吧。来年希望在这方面能够有所突破。

这一年，生活上依旧是一穷二白月光族，七月份甚至一度陷入了短暂的经济危机，虽然嘴上要强但还是靠了家里的一点救助勉强度过了经济危机，到了年底总算有所缓解。除了买书花了 4000 大洋，本年度其余花销很少，经济危机大概还是自己理财不当吧。来年希望有所改善，这样自己说话办事能够更有些底气。

这一年没有大规模的旅行颠簸，甚至小打小闹也不多，偶尔的几次故宫、景山、北海、植物园，也是被迫的。总而言之言而总之就是这一年我堕落成了一个彻底的宅男，一心一意地想着躲进小楼成一统，沉浸在自己的书香世界中，树欲静，管它风到底止不止呢。*浅层次的旅行已经不能带给我任何精神上的新知，与其花时间精力美化自己的“旅历”，倒不如多读几本书丰富下自己的“阅历”。*还是那句话，思想境界上不去，去再多的地方也属白搭，算了吧。

这一年观影约一百部，但是观影带给我的乐趣却越来越少，甚至三五个月都没有令自己心仪的影片。也许是阅读的兴趣冲淡了观影的心情吧。以前累的时候往往想看部电影放松，现在累的时候坐在椅子上写写字做做读书笔记，对我而言也是相当惬意的缓解压力愉悦身心的良方了。今年做的阅读笔记大约 200 页左右，都是一笔一划磨笔尖磨出来的，实打实的墨迹墨香。喧闹的世界里有这份心境，应该算不俗吧。

这一年我开始更多的承担家庭的责任，无论是父母那个家，还是现在这个尚未成型的家。我花了一个月的时间指导弟弟的中考，中考结束后又花了很长的时间训练他骑车旅行，替他联系更好的高中；我也开始在父母的家庭中逐渐拥有更多的话语权，期望来年我的斡旋能够让他们平安喜乐。和妞相互扶持，同甘共苦，在喧闹的世界里撑起自己片刻的安宁。

这一年如果说我有什么变化，那就是沉寂，除了沉寂，还是沉寂。

静水深流，与君共勉。

<<footnotes>>
** Footnotes:
   :PROPERTIES:
   :CUSTOM_ID: footnotes
   :CLASS: footnotes
   :END:

<<text-footnotes>>
^{[[fnr.1][1]]} 其实是被炒，sigh。

^{[[fnr.2][2]]}
对于我这样的工科男而言，文学的、心理的、历史的都可以在某种程度上归到人文类书籍里面，笑。

^{[[fnr.3][3]]} 这点很遗憾，也是我对公司最不满意的地方

 
