** 离开

离开百度已经一年多了。

间或有人问我为什么要离开百度。找工作的时候问，工作了几个月后还是会有人问。我怎么
回答这个问题呢？说 A) 试用期没通过不得不卷铺盖走人？还是说 B) 自己工作不爽主动离
职？事实上我多数情况下会选择说 B。被炒鱿鱼这种事当然是不光彩的，只是有的时候懒得
解释，也就随便撒个小慌，一笑而过。我会跟人家说，他娘的我也想炒掉那个操蛋老板，只
是我没有那个权利，被暗算了吗？

间或也有百度的同事打来电话，跟我抱怨说工作上如何束手束脚无法施展。两个月前，
Robin一封 [[http://it.sohu.com/s2012/baiduzhengfeng/][狼性邮件]]，将百度推向了舆论的风口浪尖。可是通篇读下来，我只看到了两个
字——“吃人”。

** 狼性

中国的领导似乎都有一个毛病，那就是总以为自己高高在上[1]，神圣不可侵犯。事情做
好了，功劳都是自己的，心情好了赏仨瓜俩枣给手底下辛苦干活的员工；事情搞砸了，就开
始埋怨员工不好好干活，没有“奉献自己 100% 的热血和青春”。

10 年初 Google 退出中国后，百度已然躺在印钞机上数了两年的钱，其员工规模也从不到
五千人膨胀到了接近两万人。不过，在电子商务、云计算和移动互联网的大潮下，这艘航母
似乎还没有找到自己的航向，在通往未来的路上越走越偏……

无可否认，在中国互联网的发展历史中，百度占有举足轻重的地位（废话一），创造了多个
中国第一（废话二），即便在百度略显疲惫衰落的今天，它依然是中国互联网界当之无愧的
三大巨头之一（废话三）。这里有（一些）中国顶尖的工程师，（比较）海量的数据，（比
较）庞大的机器规模以及许许多多在很多公司、高校和实验室都无法找到的学习工作环境
（废话四，你能指望学校的实验室搭建千台规模的集群供你把玩吗？）可是我们也异常遗憾
的看到，[[http://e.baidu.com][凤巢]]以后：

- 百度已经很久没有推出令人耳目一新的产品了（典型的如 03--06 年的知道、百科和贴吧）
- 百度迄今为止所有的国际化努力都是失败的
- 在电子商务、移动互联网和云计算方面，相比较其余互联网公司，百度毫无建树

一个手握百亿现金流，掌握中国互联网生杀大权的公司，竟然几年之内拿不出响当当的产品，
Robin 首先想到的是员工不够拼命，因此任何“有良好背景，流利英语，稳定的收入，信奉
工作只是人生的一部分，不思进取，追求个人生活的舒适才是全部”的人，都是小资，都是
要被淘汰的。可是我不明白的是，“信奉工作只是人生的一部分”，“追求个人生活的舒适”，
这个有错吗？绝大多数的人死之前，想到的不是工作，而是家庭、朋友、亲情。人之所以成
为人而不是一部工作机器，正是因为人生中有比工作更为重要的东西。我热爱我的家庭朋友，
也享受下班归来灯下漫笔读书的时光，这个有错吗？

没错，作为老板，你当然可以挥舞着狼牙大棒叫你的员工一边加班一边喊爽，但这种所谓狼
性是由上而下的，不会长久。我认为，百度当今最大的问题在于上下异心。上层想要业绩要
改变要漂亮的报表，中层欺上瞒下只看 KPI，每天想着怎样弄份漂亮的报表好生存下去越爬
越高，而底层技术人员确实想做一些技术上的事情，但被中层经理压制，有心无力。技术上
不去，一切都是空谈，所谓的业绩报表，除了欺上瞒下，就是自欺自娱。房地产企业的土地
房子可以升值，但互联网企业的代码机器却会腐朽。

** 岁月

即便算上实习，我在百度待的时间也只有九个月，不到一年。从最初的新鲜兴奋，到最后悲
剧性的离开，这期间各种人事变动、技术思考，我几乎从未在博客上写过。今日趁着记忆尚
存，偏又莫名辗转难眠，权且将自己在百度的经历，以及自己对工作的一些思考记录下来，
希望对后来人有些帮助。其中陈述可能有失公允，欢迎讨论和指正。

以下逐条列出百度之“怪现状”

*** 百度论语的洗脑文化

当代企业最爱做的事情就是给新员工洗脑，洗脑的内容也无非就那么几项，一是你现在的公
司多么多么好，二是你现在的老板多么多么圣明，三是你现在的工作对公司多么多么重要
（对，后勤工作对公司也很重要，搞卫生扫厕所的就更不用提了），四是即使你当前的工作
不怎么重要不怎么有趣不怎么符合你的预期只要你好好工作那么多年媳妇熬成婆你总会有出
头之日的。洗脑本来无可厚非，特别是在天朝这种神奇的国度里。只是百度也搞这一套，倒
真是让刚刚实习入职的我大跌眼镜。我记得那个时候刚刚入职实习的时候发了一本 [[http://book.douban.com/subject/4185489/][《百度
论语》]]，然后每周开例会的时候，一组人做一圈，每周学习一条，轮流说心得报告，总共
29 条，可以学习半年了。事实上这本书也不是什么不好的书，但这种学习的方式总让我想
起七十年代人手一本《毛泽东语录》的场景。书中 Robin 被写的近乎完美神化，可是我却
从来没有看到过百度内部哪里有关于失败产品（典型的比如百度 Hi、有啊）的总结。

*** 封闭的技术开发

中国的互联网企业都有一个毛病，那就是没有开源共享的精神，对开源社区索取大于回馈，
百度也是如此。这些企业总是以为自己的技术高人一等，又不想做那些”琐碎“的基础工作，
将开源的项目拿过来修修补补贴点牛皮藓后就开始到处吹牛逼说什么世界领先国内一流。比
如我在的时候，百度宣称自己的 Hadoop 集群在规模、负载和利用率上是世界前三的。可是
这又有什么用呢？第一，Hadoop不是百度开发的，百度只是打了点补丁做了些定制而已；第
二，百度的 Hadoop 集群数量只有 10+ 个，远远比不上 Google 100+ 个 GFS 集群这样的规
模，其整体的自动化运维水平也差了一个世代；第三，百度所做的所有“改进”很少回馈过开
源社区。

其实在 Hadoop 之前，百度也曾想过开发自己的 GFS + MapReduce + BigTable，没错，百
度想要开发的系统就是基于 Google 那三篇著名的论文的[2]。这个系统叫做 Pyramid，其
领衔人是[[http://zh.wikipedia.org/wiki/%E7%8E%8B%E9%80%89][王选]]的高徒[[http://blog.sina.com.cn/kern0612][阳振坤]]博士。Pyramid 大约开发了 2--3 年，最终以失败告终，据说最
后与 Hadoop PK 的时候完败下来，阳振坤也在其后离职加盟淘宝[3]。我不知道 Google 开
发 GFS + MapReduce + BigTable 用了多久，但是 GFS 的论文是 03 年，MapReduce 论文
是 04 年，BigTable 应该是 07 年，想来 Google 应该也是开发了 4--6 年左右的时间。
Pyramid 的失败直接导致了 Hadoop 在百度的崛起，不到两年，Hadoop 的机器数量从无到
有，很快就突破了万台的规模，并且机房也从北京开始像长三角扩展，百度也终于迈出了跨
数据中心的步子，尽管这个步伐似乎比 Google 慢了 5--8 年？[4]

不过百度虽然自己用 Hadoop 用得很 High，负载什么的，报表都弄得不错，集群规模也上
了国内少有的 3000+ 台，但是却很少对 Hadoop 社区进行开源回馈。其内部 Hadoop 是基
于 Hadoop 0.19--0.20 改进的。这样做的好处就是快，一方面依赖社区拿到已有的代码基，
整合测试就可上线，同时也不用管什么伦理道德奉献回馈的鸟事，但其缺点就是内部的
Hadoop 和官方的 Hadoop 会逐渐越走越远，上游的 Patch 和改进越到后来会越难引进合并。
这样做的结果就是和社区分离，用自己一人之力对抗全球智慧，最终只能自讨苦吃[5]。

我记得有一次内部年会上，有位工程师跳起来问，“公司可不可以做一些开源的产品呢？很
多东西本来就是从外边拿过来的。”我只记得当时台上的两位高管，其中一位女高管脸色稍
变，过了一会又开始讲什么“做开源需要时间精力；好的东西才好意思开源出去，否则会丢
脸”什么什么的。我想， *一个 IT 公司有没有勇气拥抱开源，是一个公司是否对自己的技
术有足够自信的一个表现。* 在这方面，百度乏陈可善，不但没有代码，连论文也很少。而
淘宝在章文嵩的带领下，其开源已经做的如火如荼，算是国内 IT 企业中开源做的最好的一
个。

*** 世界上最优秀的工程师？

百度的内部邮件中不止一次的提到“世界上最优秀的工程师”这个字眼，可惜作为这封邮件的
收件人，连我们自己都不相信自己是世界上最优秀的工程师。09--11年高速扩张的两年，百
度的招人标准降低了很多。这也是无可奈何的事情，毕竟中国的人才储备有限，有时候即便
你想花钱，也不一定能招到足够的人。

你当然无法否认，百度内部有很多牛人，可是大凡拿得上台面的公司，那个手里没有一些牛
人呢？重要的是保证整体人才的平均质量，而不是树立几个典型，然后就自吹自擂说自己的
工程师是世界上最优秀的。

*** KPI 为王

我在 Hadoop 运维组做到第 4 个月的时候，一手创立 Hadoop 运维的经理走了，空降了一
位新来的经理。当然，这位经理是不懂 Hadoop 的，加上他又实在繁忙，所能做的就是从报
表入手。比如说每周几千台机器几百条小报警有没有都处理掉，预算做的怎么样，总之都是
报表性的东西。至于技术上的，监控怎么做，如何才能更好的自动化，怎样统一归约化的整
合集群的各个系统，从来就不是他关心的重点。我辛苦两周做出来一个小的监控系统，可以
自动的检测各个集群的一些指标参数，并且支持自定义插件，自动化的生成监测报告发送到
邮箱中，他给的评价是“这算啥，T2 的工程师都能做”。我当时特别火也特别委屈，心里想
“T2 的工程师都能做，可是为什么一直没有人做呢？站着说话不腰疼”。

再比如我们每周都要写 Hadoop 集群运维周报，内容无非是去几个监控系统上鼠标
Copy/Paste 一些数据到一个模板里。其实这样的东西完全可以稍微花些人力写点程序抓点
网页完成，可是一直没有人做这个事情，大家就这样一周一周的写下来。反正经理要的就是
这个，谁管你怎么得来的呢。

当一家技术公司由技术驱动变成 KPI 驱动的时候，也就意味着这家公司发展到了一个瓶颈
期。不断有前同事跟我聊，说自己想做一些事情，但是经理不让。为什么呢？比如说一个4、
5 年的产品代码，由于人员的交替加上技术的封闭，必然是有很多丑陋的代码的，这个时候
后来接手的人如果是个有责任心又有代码洁癖的人的话，自然就想对代码做些重构和改进。
这就带来了一个问题：万一由于这种额外的改动造成产品出现事故，怪谁？经理是不想承担
这样的责任的，因为百度的经理不写代码，多一事不如少一事。这样一个技术人员的积极进
取心就这样被压制了。还有的经理说：“做，可以做，如果一个星期之内可以完成，就去做”。
可是有多少伟大的产品是一个星期内完成的呢？GFS 不是，MapReduce 也不是。可是经理才
不会管这些，他关心的是他的 KPI，是报表。一个东西，如果短期内无法出成果，就不要做。

所以像 Puppet 这样的工具是不可能出自百度之手的。即便是工程师在平时的工作之中有一
些思考，但也很少能有时间形成系统化的，并且能够走出百度被业界认可的东西的。

*** 会议，还是会议；总结，还是总结；沟通，还是沟通

百度的会议之多，总结之烦，沟通之杂简直是令人闻风丧胆。我在百度的时候，每周至少开
3 个会，每个会不少于 1 个小时；每天发送查看邮件不少于 40 封；每天花在 Hi 上交流
的时间不少于 3 个小时。有人会问，这么多的沟通会议时间，还有时间干正事嘛？怎么会
需要这么多时间沟通交流呢？首先是百度非常看中邮件文化，所有事无论大小都要有个邮件
性的总结，学会设定邮件规则是每个百度人的第一课；其次就是百度的部门极其多，据统计
整个公司大概有 500 多个部门和组，工种单一，想要完成一个 Project 需要跨越很多部门。
这就导致了百度内部的沟通成本一直居高不下，会议室都要提前一周甚至两周才能订上。很
多 RD 都是上午过来处理邮件，下午开会，然后晚饭后写代码[6]。


*** 自由上班？Shit

百度号称自由上班，但这个所谓的自由上班，每天 8 小时只多不少[7]。

*** 部门隔离

没错，百度虽然号称“简单可依赖”，“不唯上”，平等，无“公司政治”的企业文化，但是由于
部门繁多，流程繁杂，真的想做一件事情，如果没有自上而下的推动，光预算、排期、开会
就要耗掉几周甚至几个月的时间。

另一方面，如果你去仔细观察百度的产品，你会发现百度的产品风格差异极大。无论是网页
产品还是客户端产品，其 UI 方面从来都没有给人一种非常明朗统一的感觉，能够让人一看
就知道这是百度的东西。这方面，苹果做的最好，Google 次之，百度毫无章法。

*** Geek在哪里？

百度并不是一个 Geek 公司。Facebook 是，Google 是，但百度不是。大多数工程师还在用
着 10 年前的 XP 系统，用着盗版的 Office 和 SecureCRT 软件登录 SSH 写着各种文档和
代码。百度的工程师没有追求美感的习惯，这种美感包括但不限于代码风格、文档排版、产
品设计等。据我所知，Google 的所有代码在提交之间都会经过一系列的检查，但百度至今
没有如此完善的流程。至少在我们组，代码写了一年多，才想到要重新整理，规整风格。百
度内部的 wiki、代码审查，项目管理系统从来也是破破烂烂，没有类似于 Facebook
[[http://phabricator.org/][Phabricator]] 这样的系统。

*** 有啊

百度历史上有很多失败的产品，但是从来没有一个产品，如有啊这般惨烈悲壮[8]。这样的
人，这样的团队，这样的条件下这样的时间内做出了这样的牺牲和这样的业绩，但最终依然
无法摆脱失败的命运。有的时候，我真的怀疑，当你怀着“我坚信让我一往无前的唯一力量
就是我热爱我所做的一切”这样的信念去努力去拼搏的时候，你的老板能够看到并且认可你
的付出吗？有啊的惨败，百度的高管可曾做过认真的反省？这究竟是公司战略上的问题还是
员工的问题？员工犯错可以扣钱扣绩效，但如果是公司犯错呢？公司做过这样的检讨吗？

** 无他

最终导致我离职（或者被炒掉）的事件是因为一次不快的沟通。那次沟通中经理对我做出了
“好高骛远”的评价，并且不认可我平时业余时间 KPI 之外的工作成果，说我的东西“连 T2
的工程师都可以做”。而我当然不认可这种评价，当面顶撞了他，说“不认可这种评价”。这
可能直接导致经理认为我是个刺头，无法约束，干脆开掉为好。于是在我转正前一周我接到
通知让我滚蛋走人。我将此事告知了我前面三个月的导师，他表示非常震惊。HR 也特别奇
怪，说一个人怎么前面三个月好好的，到了快要转正的时候突然就被开掉了。

回家之后，我跟妞说，“不以物喜，不以己悲”，《[[http://xiaohanyu.me/posts/2012-07-13-live-my-live-for-half-a-year/][偷得浮生半年闲]]》。


** 箴言

一个人工作的价值（狭义上讲是薪水）正比于这个人的不可替代性。

“谢谢你们曾经看轻我”。

“即使缤纷落尽，繁华消亡，青春绝版，也不要被生活磨平了棱角”。

[1] [[http://www.hecaitou.com/blogs/hecaitou/archives/134608.aspx][和菜头：放开那些员工]]，[[http://www.hecaitou.com/blogs/hecaitou/archives/134609.aspx][和菜头：得罪得罪]]

[2] 所以你千万不要相信百度说自己和 Google 在竞争，事实上如果没有 GFW“贸易保护”的
话，百度根本没有和 Google 竞争的技术实力。你要相信，无论是从技术、人才、基础设施
和营收上来比，百度和 Google 都不是一个级别上的公司。

[3] 关于这个项目更多细节，可以参考内部人士尚未写完的 [[http://www.leafok.com/blog/2012/08/05/%E3%80%8Apyramid-%E4%BC%A0%E5%A5%87%E3%80%8B_%E5%89%8D%E8%A8%80%20/][Pyramid 传奇系列]]，我接手
Hadoop 运维的时候，Pyramid 已经下线了，只在 Wiki 上看到过只言片语

[4] Oh，5--8 年，IT 的一个朝代都过去了

[5] 国内 IT 企业对待开源大多如此，但是有些企业已经开始觉醒，比如[[http://www.openstack.org/blog/2012/10/how-sina-contributes-to-openstack/][新浪之于 OpenStack]]

[6] 参考：[[http://blog.sina.com.cn/s/blog_68baa8630101azav.html][一个前百度工程师看百度的狼性]]

[7] 参考：[[http://hi.baidu.com/rodimus/item/2840aad3d3da52e5b2f777c5][工作这些年]]

[8] 参考：[[http://hi.baidu.com/dongbao/item/e5d36f19181af317e2f98649][东宝：为了即将忘却的记忆 ]]

------

这篇文章发表半天后，由于某位不知名的百度仁兄的抬爱，忽然的就火了起来，也吓了我一
跳。我写了另外一篇小文作为补充说明：《[[http://xiaohanyu.me/posts/2013-01-26-fewer-words-more-thoughts/][慎言多思]]》。如有任何建议指正，欢迎多多指
教，xiaohanyu1988@gmail.com。

另，很多人提到说题目有些“驴唇不对马嘴”，我这里稍微解释下。首先我是明白“罪己诏”这
三个字的含义的，取这三个字为题也是有意为之；其次是写这篇文章的初衷是为了“批判”下
Robin 的那封狼性邮件，因为我觉得百度出现的很多问题是公司层面的而非员工层面，绝不
是为了博眼球。想来想去还是觉得这个题目比较好，加上引号，算一点修正，剩余不再修改。
谢谢诸位提醒。
