去年12月份的时候我曾经给自己写了一份"OpenStack开发基础知识"书单，贴在墙上，书单大概如下：

-  网络基础：

   -  [[http://book.douban.com/subject/4793807/][+Foundations of Python
      Network Programming+]]
   -  [[http://book.douban.com/subject/2970300/][+计算机网络+]]
   -  [[http://book.douban.com/subject/1440226/][+HTTP+]]
   -  [[http://book.douban.com/subject/10531427/][计算机网络教程]]
   -  [[http://book.douban.com/subject/1095214/][TCP/IP详解]]
   -  [[http://book.douban.com/subject/2016013/][+Internetworking+ With
      TCP/IP]]

-  语言基础：

   -  [[http://book.douban.com/subject/4249385/][+Pro Python+]]
   -  [[http://book.douban.com/subject/4086938/][Metaprogramming Ruby]]

-  JavaScript:

   -  [[http://book.douban.com/subject/1869705/][+JavaScript+
      高级程序设计]]
   -  [[http://book.douban.com/subject/3012828/][JavaScript语言精髓与编程实践]]

-  Web Design

   -  [[http://book.douban.com/subject/10448952/][+The Definitive Guide+
      to HTML5]]
   -  [[http://book.douban.com/subject/1937913/][无懈可击的Web设计]]

-  [[http://book.douban.com/subject/6000169/][+Rabb+itMQ in Action]]
-  Database

   -  [[http://book.douban.com/subject/3354490/][+MySQL必知必会+]]
   -  [[http://book.douban.com/subject/3182110/][数据库系统基础教程]]
   -  [[http://book.douban.com/subject/1173549/][数据库设计教程]]

-  Django

   -  [[http://book.douban.com/subject/3617254/][+The Definitive Guide
      to+ Django]]
   -  [[http://book.douban.com/subject/3086812/][Pro Django]]

读书进度=书名中划线部分的长度/书名的长度。之所以有这份书单，是因为在前面几个月的开发中，我发现自己的基础知识薄弱，远远不能满足OpenStack开发的需要。虽然自己已经能够按照公司的基本要求，照猫画虎地开发出几个能用的所谓Feature，但是我内心明白，自己的能力上尚不足以透彻理解OpenStack代码^{[[fn-.1][1]]}。

我认为自己还算是一个比较努力的人，并且自认为对自己目前所从事的行业还是有着满心的热爱和期待，期待自己能做出一些有用的产品，留下一些真正有用的能改善人们生活的东西。这个宏大的愿望映射到眼前，就是努力使自己成为一个合格的Full-Stack类型的Web开发工程师。而进一步将眼前目标付诸行动，就是上面的书单了。我原本定的时间是3-5个月左右，不过现在看来还是太狂妄太浮躁了。客观上是自己要工作，时间不完全都是自己的；主观上则是自己“深度优先，随性而为”的阅读习惯常常会不自主的打乱原本订好的读书计划。比方说我在读"Pro
Python"的时候为了搞清楚细节会去读"[[http://book.douban.com/subject/3117898/][Python源码剖析]]"，会去尝试理解Python的[[http://python3.blogspot.com/][整个历史]]；在读"HTTP"的时候为了理解[[http://en.wikipedia.org/wiki/Representational_state_transfer][ReST]]，会去读"[[http://book.douban.com/subject/4791069/][REST
in Practice]]"； 而我在尝试理解Python
[[http://en.wikipedia.org/wiki/Test-driven_development][TDD]]的时候会把Ruby中关于[[http://cukes.info/][Cubumber]]的书加入阅读计划。这或许不是一个良好的阅读习惯，但这能保持我的兴趣，这就够了。

我不是一个Top的工程师，至少目前不是------Top的工程师不会像我一样还在费力的学习理解ReST/TDD这些概念性的东西。我知道Top的工程师在哪里
^{[[fn-.2][2]]}。这类人天赋异禀，并且在很早的时候就接触计算机。在你还在骑着自行车围着院子绕圈的时候他们已经开始理解算法和数据结构，在你刚刚写出"hello
world"的时候他们已经能写出成型的软件作品，在你毕业之际为找工作焦头烂额的时候，他们已经受过了1万小时的训练，有更好的机会和最聪明的人合作更快的提高自己。这个博客基本上忠实记录了我正式开始认真学习计算机的全部历程。四年来我几乎做过各种各样的东西，Windows手机开发，Java
SSH(已经忘光光)，OpenGL程序，Hadoop，Python/FFmpeg写的转码系统等等，很杂，也很浅。但我一直坚持一个方向，就是拥抱开源，先是尝试学习基础知识，用好Linux/Emacs这类基本工具，毕业工作后开始去尝试读一些开源代码，提一些无关痛痒的patch试图接近开源，这一年来又开始尝试理解OpenStack，并真正的提交了一些patch。我不敢评价OpenStack的设计是否优秀，事实上我还没有这个能力去完全理解它，更妄论评价了。但是OpenStack的开发确实让我学到了很多东西，我开始理解了TDD，开始逐理解了ReST和Web
Service，开始逐渐理解作为工程语言而不是脚本语言的Python，开始理解Message
Queue。而我也通过自己的努力，让基于jenkins/gerrit的自动化测试部署的全套流程在公司运转了起来。

两年前信心满满刚来北京的时候，我从未想过自己会那么快的离开百度^{[[fn-.3][3]]}，一年前开始寻找新的工作机会的时候，我完全没有听过OpenStack这个词。当初一心坚持离开学校是为了远离校园里学习的束缚，现在走向工作岗位又会感慨感叹时间的宝贵和校园里相对的自由。说白了，我是一个贪心的实用主义者，胸无大志，从来不会想五年以后的事情，学校里面不想听无聊的课程，就天南海北山山水水的疯跑，哪怕一学期挂科五门依然无所畏惧不懂屈服；工作以后顶撞上司就来个偷得浮生半年闲，躲进小楼成一统，管他春夏与秋冬，云卷云舒花开花落------但为了生活还是要出来找工作。

貌似扯的有些远了......最后回到本文的正题吧，OpenStack的开发。上个星期做了两个东西，第一是做了个OpenStack代码的国内镜像，方便教育网内学生党^{[[fn-.4][4]]}，地址是：

-  [[http://git.oschina.net/openstack]]
-  [[http://git.oschina.net/openstack-dev]]

第二是基于Vagrant做了个OpenStack的开发环境，地址是：

-  [[https://github.com/xiaohanyu/vagrant-hackerbox]]
-  [[https://github.com/xiaohanyu/vagrant-ansible-devstack]]

好了，吹牛到此结束，各位好梦晚安。

--

<<footnotes>>
** Footnotes:
   :PROPERTIES:
   :CUSTOM_ID: footnotes
   :CLASS: footnotes
   :END:

<<text-footnotes>>
^{[[fnr-.1][1]]}
比如我至今依旧没完彻底理解OpenStack中基于[[http://www.sqlalchemy.org/][sqlalchemy]]
ORM的数据模型，基于iptable/openvswitch等的底层网络原理，更妄想理解kvm/xen/内核这类CS工程领域真正“高富帅”的东西了。事实上，如果没有扎实的数据库/网络/操作系统知识，要彻底理解这些东西是很难的。

^{[[fnr-.2][2]]}
比如[[http://tianyicui.com/][这里]]，[[http://blog.peakji.com/][这里]]和[[https://www.byvoid.com/][这里]]。

^{[[fnr-.3][3]]} 也从未想到过自己的一篇文章能引起那么大的争议。

^{[[fnr-.4][4]]}
顺便吐槽下北大的校园网，30元/80小时，50元/160小时，90元不限时包月，超时流量1元/MB，这价格都快赶上北京正常的联通宽带了。而且速度那么慢(github
clone
20k/s)，北京联通现在可是号称20M光纤入户的。这就是世界一流大学的校园网，可笑。

 
